### ISSUE TITLE
can't send to Chrome default profile without creating a custom 'open with'

### ISSUE THREAD

**Issue by Sopor** [darktrojan/openwith#131]
`Open with` can automatically detect existing browsers but if i add more Chrome profile i can't add any arguments to the existing `open with Chrome`. I have to create a new and add `--profile-directory="Default"`.
So why can't these automatically detected web browser accept arguments as those i add by myself? So now i need to create two custom `open with` and hide the automatically detected.
This issue must apply to all the other web browsers too when you create (i haven't installed `open with` when i already have more than one profile so i don't know how it handle it) more profiles.

Open with: 6.8.1
Firefox: 54.0.1 (64-bit)
Windows 8.1

**Comment by Sopor-** [comment]
And now i have found that hide or change name doesn't work. So now i have three Google Chrome open with :(
When i press the `Hide` button it change to `Show` and when i reopen the options it is back to `Hide`. If i open the menu i can see that Google Chrome i tried to hide is still there.

**Comment by darktrojan** [comment]
The auto-detected entries can't be edited because they're loaded from the Windows registry every time Firefox starts. (You could actually change the registry entry but I'll let you figure that out for yourself.)

I'm not sure what's going on with your Hide/Show buttons but they work for most people!

By the way, I'm having to completely rewrite Open With to be compatible with Firefox 57, and it won't have either of the issues you've mentioned here.
