### ISSUE TITLE
Directory PROFILE/.local/share

### ISSUE THREAD

**Issue by nazir-cz** [darktrojan/openwith#134]
Hello!
SeaMonkey 2.49.1, or FireFox 55.0.3, Linux x86_64, Open With 6.8.1

After every browser startup, an empty .local/share/ directory is created in its current user profile.
It's not a dysfunctional error, but could it be please fixed?

**Comment by darktrojan** [comment]
Wow.

I found the code in question. It hasn't changed since I wrote it four years ago, and has never worked as intended due to two mistakes. The directories created are an unintended consequence I either didn't know about or long since forgot.

Having said that, the code is going to be obsolete in a few weeks when the WebExtension arrives. But I might as well fix it since there'll be one last release before then.
