### ISSUE TITLE
Add "Open with" functional to link menu (opened on right click on link in page) in Firefox for opening links in external app

### ISSUE THREAD

**Issue by MurzNN** [darktrojan/openwith#48]
Very often I need to open ftp, sftp, file://myfolder/ and other type of links via external application instead of current browser. At now I can't find any extension or solution for Firefox to open links with external app. 
And I find your extension, that do this thing, but available only on already opened url as web page. 

Can you create new option in config for add "Open with" menu item in Firefox right click menu for all links on page? Or maybe produce separate extension for this small feature. Thanks!

**Comment by VADemon** [comment]
1) You don't need to open a page in order to use Open With on it. Right-click on the desired link and use Open With through that context menu. (Afaik, requires changing OW options)

Secondly, you wouldn't want to open ALL links in most cases. Take Youtube as an example.

Excuse me, if I misunderstood you. Your English is... ;)

**Comment by MurzNN** [comment]
Oh, sorry, I didn't see this option in config page. And sorry for my English, it is not so good.
