### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by maxigaz** [darktrojan/openwith#53]
With Pale Moon 25.6.0, the latest version of Open With... that I can update to is 5.6.3.1. (When trying to install it from AMO, it says it is compatible.)

The main problem with this version is that I cannot create two entries with the same executable with different arguments. I don't have this issue with 5.9, which works fine with Firefox.

Edit: another problem is that mpv cannot be used with the parameter `--ytdl-format="bestvideo[height<=?1080]+bestaudio/best" --profile=pseudo-gui --` with the older version of Open With... under Linux.

Is it possible to make the latest version (and the future ones) work with Pale Moon?

**Comment by darktrojan** [comment]
I don't support Pale Moon and I have no real intention of doing so, *but* later versions of Open With should mostly work with it. I suspect you'd have to download the .xpi and alter the compatible version numbers in `install.rdf`.

**Comment by notargets** [comment]
OK, I've tried editing `install.rdf` and installing V6.0 that way. Although the issues I mentioned above are resolved now, the toolbar buttons that belong to Open With... are completely missing, unfortunately, even in the Customize... view.

**Comment by LimboSlam** [comment]
@darktrojan: Are your views about supporting us still the same? I can confirm what @maxigaz said, the only thing really missing is the toolbar buttons. A lot has changed since then, especially Pale Moon. You should have a look around and you'll be surprised how much they accomplished in just those two years of this issue being opened: https://www.palemoon.org/.  

I'm using a tool to help test compatibility issues with Pale Moon v27, which is hosted at [APMO](https://addons.palemoon.org/extensions/moon-tester-tool/).
